### PR TITLE
Describe project purpose more clearly

### PR DESCRIPTION
**Pull request by ShaneSharareh**
Hello Caleb, 

I have updated the README to contain some information of the purpose of our sandbox project, as well as to have some style.

Please let me know what you think, and if there is any changes I should add to it.

Shane

### CODE REVIEW

**Comment by caleb531** [comment]
This is looking great. What do you think about changing the heading from reading "The Readme" to "GitHub Sandbox"? I think that would be clearer to new devs looking at the project for the first time.

**Comment by ShaneSharareh** [comment]
Hi Caleb,
I have changed the heading from "The Readme" to "Github Sandbox" as you requested,
How is it looking so far?

**Comment by caleb531** [comment]
Looks better! Two more small suggestions before I'm ready to merge this in:

1. Remove the "and" in the copyright notice to read "Copyright 2016 Caleb Evans, Shane Sharareh" (the "and" is unnecessary and reads awkwardly with the comma already in place)
2. Properly capitalize "github" as "GitHub"

**Comment by ShaneSharareh** [comment]
Great Suggestion Caleb,
I have fixed the requested changes.

Shane

**Comment by caleb531** [comment]
LGTM! I'll merge in now. :)

**Pull request merged**
